name: Outputs

on: workflow_dispatch

jobs:
  gen-outputs:
    runs-on: ubuntu-latest
    outputs:
      message: ${{steps.random-num-gen.outputs.number }}
 
    steps: 
      - id: random-num-gen
        run: |
          echo "number=101" >> $GITHUB_OUTPUT
          echo "msg=Ramdom Number" >> $GITHUB_OUTPUT
  dis-outputs:
    needs: gen-outputs
    runs-on: ubuntu-latest
    steps: 
    - id: random-num-dis
      run: echo '${{needs.gen-outputs.outputs.message}}'
